# AzusaCoordinates Configuration

# Show player coordinates
show_coordinates: true

# Show last coordinates at death
show_death_coordinates: true

# Message to display last coordinates on death
last_death_message: "Last Coordinates When You Died: §f[§e%s§f] §f[§e%d, %d, %d§f]"

## %s = World
## %d = Player Coordinates